version: "0.1"
services:
  ofpython:
    build: ./
    container_name: ofpython
    image: ofpython
    volumes:
      - C:\shared:/home/damian/sharedVol
      - C:\Users\dasni\OneDrive - Uniwersytet Wrocławski\MGR\MGR_code\IFPM2D:/home/damian/MGR/2D/IFPM2D
      - C:\Users\dasni\OneDrive - Uniwersytet Wrocławski\MGR\MGR_code\IFPM3D:/home/damian/MGR/3D/IFPM3D

volumes:
  shared: