name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: [ "Dockerfile", "pyproject.toml", "poetry.lock" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "Dockerfile", "pyproject.toml", "poetry.lock" ]
  workflow_dispatch:          # manual "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fpm:ci